<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SoalPilgan;

class SoalPilganSeeder extends Seeder
{
    public function run(): void
    {
        $soals = [
            // sistem pencernaan
            [
                'slug' => 'sistem-pencernaan',
                'nomor' => 1,
                'pertanyaan' => 'Apa fungsi utama enzim amilase dalam proses pencernaan?',
                'opsi_a' => 'Memecah lemak menjadi asam lemak',
                'opsi_b' => 'Mengubah protein menjadi asam amino',
                'opsi_c' => 'Mengubah karbohidrat menjadi gula sederhana',
                'opsi_d' => 'Menyerap air dalam usus besar',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Enzim amilase berfungsi untuk memecah karbohidrat kompleks (seperti pati) menjadi gula sederhana (seperti maltosa dan glukosa), dan proses ini dimulai di dalam mulut.',
            ],

            [
                'slug' => 'sistem-pencernaan',
                'nomor' => 2,
                'pertanyaan' => 'Organ manakah yang berperan utama dalam penyerapan nutrisi?',
                'opsi_a' => 'Lambung',
                'opsi_b' => 'Mulut',
                'opsi_c' => 'Usus besar',
                'opsi_d' => 'Usus halus',
                'jawaban' => 'D',
                'poin' => 10,
                'penjelasan' => 'Usus halus adalah tempat utama penyerapan nutrisi dari makanan yang telah dicerna, karena memiliki permukaan luas dengan banyak vili yang menyerap zat gizi.',
            ],

            [
                'slug' => 'sistem-pencernaan',
                'nomor' => 3,
                'pertanyaan' => 'Apa nama proses pergerakan makanan di sepanjang saluran pencernaan?',
                'opsi_a' => 'Filtrasi',
                'opsi_b' => 'Peristaltik',
                'opsi_c' => 'Difusi',
                'opsi_d' => 'Emulsi',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Peristaltik adalah gerakan otot secara ritmis dan bergelombang yang mendorong makanan melalui saluran pencernaan, mulai dari kerongkongan hingga usus',
            ],

            [
                'slug' => 'sistem-pencernaan',
                'nomor' => 4,
                'pertanyaan' => 'Zat apa yang dihasilkan hati untuk membantu mencerna lemak?',
                'opsi_a' => 'Enzim tripsin',
                'opsi_b' => 'Asam klorida',
                'opsi_c' => 'Empedu',
                'opsi_d' => 'Insulin',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Empedu diproduksi oleh hati dan disimpan di kantong empedu. Empedu berfungsi untuk mengemulsikan lemak agar lebih mudah dicerna oleh enzim lipase.',
            ],

            [
                'slug' => 'sistem-pencernaan',
                'nomor' => 5,
                'pertanyaan' => 'Dimana proses pencernaan makanan secara kimia pertama kali terjadi?',
                'opsi_a' => 'Lambung',
                'opsi_b' => 'Mulut',
                'opsi_c' => 'Usus halus',
                'opsi_d' => 'Kerongkongan',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Pencernaan kimia pertama kali terjadi di mulut, di mana enzim amilase dalam air liur mulai memecah karbohidrat menjadi gula sederhana.',
            ],
            
            // sistem-pernapasan
            [
                'slug' => 'sistem-pernapasan',
                'nomor' => 1,
                'pertanyaan' => 'Apa fungsi utama alveolus dalam paru-paru?',
                'opsi_a' => 'Menangkap virus',
                'opsi_b' => 'Mengangkut udara ke otak',
                'opsi_c' => 'Pertukaran gas antara O2 dan CO2',
                'opsi_d' => 'Menjaga kelembaban kulit',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Alveolus adalah kantong udara kecil di paru-paru tempat terjadinya pertukaran gas oksigen (O2) dan karbon dioksida (CO2) dengan darah melalui dinding kapiler.',
            ],

            [
                'slug' => 'sistem-pernapasan',
                'nomor' => 2,
                'pertanyaan' => 'Bagian sistem pernapasan yang menghubungkan trakea dengan paru-paru adalah...',
                'opsi_a' => 'Bronkus',
                'opsi_b' => 'Laring',
                'opsi_c' => 'Alveolus',
                'opsi_d' => 'Hidung',
                'jawaban' => 'A',
                'poin' => 10,
                'penjelasan' => 'Bronkus adalah cabang dari trakea yang mengarah ke masing-masing paru-paru. Bronkus membawa udara dari trakea ke paru-paru dan sebaliknya.',
            ],

            [
                'slug' => 'sistem-pernapasan',
                'nomor' => 3,
                'pertanyaan' => 'Organ yang berperan sebagai tempat keluar masuknya udara adalah...',
                'opsi_a' => 'Hati',
                'opsi_b' => 'Paru-paru',
                'opsi_c' => 'Jantung',
                'opsi_d' => 'Ginjal',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Paru-paru adalah organ utama dalam sistem pernapasan yang menjadi tempat pertukaran udara, yakni pengambilan oksigen dan pembuangan karbon dioksida.',
            ],

            [
                'slug' => 'sistem-pernapasan',
                'nomor' => 4,
                'pertanyaan' => 'Apa yang terjadi saat kita menghembuskan napas?',
                'opsi_a' => 'Otot diafragma menegang',
                'opsi_b' => 'Otot dada mengembang',
                'opsi_c' => 'Paru-paru menyusut dan udara keluar',
                'opsi_d' => 'Trakea membesar',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Saat menghembuskan napas, otot diafragma dan otot dada relaksasi sehingga paru-paru menyusut, dan udara kaya karbon dioksida keluar dari tubuh.',
            ],
            [
                'slug' => 'sistem-pernapasan',
                'nomor' => 5,
                'pertanyaan' => 'Gas apa yang paling banyak dihirup manusia saat bernapas?',
                'opsi_a' => 'Karbon dioksida',
                'opsi_b' => 'Hidrogen',
                'opsi_c' => 'Oksigen',
                'opsi_d' => 'Nitrogen',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Nitrogen merupakan gas yang paling banyak dihirup, sekitar 78% dari udara atmosfer. Namun oksigen (sekitar 21%) adalah gas yang digunakan tubuh untuk respirasi.',
            ],

            // sistem rangka
            [
                'slug' => 'sistem-rangka',
                'nomor' => 1,
                'pertanyaan' => 'Apa fungsi utama sistem rangka pada tubuh manusia?',
                'opsi_a' => 'Mengatur suhu tubuh',
                'opsi_b' => 'Membantu pernapasan',
                'opsi_c' => 'Memberi bentuk dan mendukung tubuh',
                'opsi_d' => 'Menghasilkan energi',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Sistem rangka memberikan bentuk pada tubuh, menopang struktur tubuh, serta melindungi organ-organ vital seperti otak, jantung, dan paru-paru.',
            ],

            [
                'slug' => 'sistem-rangka',
                'nomor' => 2,
                'pertanyaan' => 'Tulang manakah yang melindungi organ otak?',
                'opsi_a' => 'Tulang rusuk',
                'opsi_b' => 'Tulang tengkorak',
                'opsi_c' => 'Tulang belakang',
                'opsi_d' => 'Tulang panggul',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Tulang tengkorak melindungi otak dari benturan dan cedera, serta menjadi tempat menempelnya otot-otot wajah dan kepala.',
            ],

            [
                'slug' => 'sistem-rangka',
                'nomor' => 3,
                'pertanyaan' => 'Apa nama hubungan antar tulang yang memungkinkan pergerakan?',
                'opsi_a' => 'Ligamen',
                'opsi_b' => 'Sendi',
                'opsi_c' => 'Otot',
                'opsi_d' => 'Tendon',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Sendi adalah tempat pertemuan dua tulang atau lebih yang memungkinkan terjadinya pergerakan, seperti pada siku dan lutut.',
            ],

            [
                'slug' => 'sistem-rangka',
                'nomor' => 4,
                'pertanyaan' => 'Jenis tulang manakah yang berbentuk panjang seperti pada lengan dan kaki?',
                'opsi_a' => 'Tulang pipih',
                'opsi_b' => 'Tulang pendek',
                'opsi_c' => 'Tulang panjang',
                'opsi_d' => 'Tulang tidak beraturan',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Tulang panjang memiliki bentuk silindris memanjang dan berfungsi sebagai penopang tubuh serta alat gerak, contohnya tulang paha dan lengan atas.',
            ],

            [
                'slug' => 'sistem-rangka',
                'nomor' => 5,
                'pertanyaan' => 'Tulang belakang tersusun atas sejumlah ruas tulang yang disebut...',
                'opsi_a' => 'Karpal',
                'opsi_b' => 'Vertebra',
                'opsi_c' => 'Metakarpal',
                'opsi_d' => 'Tarsal',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Tulang belakang terdiri dari ruas-ruas tulang yang disebut vertebra. Vertebra berfungsi melindungi sumsum tulang belakang dan menopang tubuh.',
            ],

            // sistem reproduksi
            [
                'slug' => 'sistem-reproduksi',
                'nomor' => 1,
                'pertanyaan' => 'Apa fungsi utama testis dalam sistem reproduksi pria?',
                'opsi_a' => 'Menyimpan sperma',
                'opsi_b' => 'Menghasilkan sperma dan hormon testosteron',
                'opsi_c' => 'Mengatur suhu tubuh',
                'opsi_d' => 'Menyaring darah',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Testis berfungsi menghasilkan sel sperma dan hormon testosteron yang penting untuk perkembangan ciri-ciri kelamin sekunder pada pria.',
            ],
            [
                'slug' => 'sistem-reproduksi',
                'nomor' => 2,
                'pertanyaan' => 'Organ yang menjadi tempat berkembangnya janin selama kehamilan adalah...',
                'opsi_a' => 'Ovarium',
                'opsi_b' => 'Vagina',
                'opsi_c' => 'Uterus',
                'opsi_d' => 'Tuba falopi',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Uterus (rahim) adalah tempat di mana janin tumbuh dan berkembang selama kehamilan, dilengkapi dengan dinding yang tebal dan banyak pembuluh darah.'
            ],
            [
                'slug' => 'sistem-reproduksi',
                'nomor' => 3,
                'pertanyaan' => 'Apa nama sel kelamin pria?',
                'opsi_a' => 'Ovum',
                'opsi_b' => 'Sperma',
                'opsi_c' => 'Zigot',
                'opsi_d' => 'Embrio',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Sel kelamin pria disebut sperma, yang diproduksi oleh testis dan berfungsi membuahi sel telur (ovum) dalam proses reproduksi.',
            ],
            [
                'slug' => 'sistem-reproduksi',
                'nomor' => 4,
                'pertanyaan' => 'Proses bertemunya sel sperma dan ovum disebut...',
                'opsi_a' => 'Fertilisasi',
                'opsi_b' => 'Ovulasi',
                'opsi_c' => 'Menstruasi',
                'opsi_d' => 'Implantasi',
                'jawaban' => 'A',
                'poin' => 10,
                'penjelasan' => 'Fertilisasi adalah proses pembuahan, yaitu ketika sel sperma bertemu dan bersatu dengan sel ovum untuk membentuk zigot.',
            ],
            [
                'slug' => 'sistem-reproduksi',
                'nomor' => 5,
                'pertanyaan' => 'Apa nama hormon yang berperan penting dalam pengaturan siklus menstruasi?',
                'opsi_a' => 'Testosteron',
                'opsi_b' => 'Adrenalin',
                'opsi_c' => 'Estrogen',
                'opsi_d' => 'Insulin',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Estrogen adalah hormon yang diproduksi oleh ovarium dan berperan penting dalam mengatur siklus menstruasi serta mempersiapkan rahim untuk kehamilan.',
            ],

            // sistem otot
            [
                'slug' => 'sistem-otot',
                'nomor' => 1,
                'pertanyaan' => 'Apa fungsi utama dari sistem otot pada manusia?',
                'opsi_a' => 'Mengatur suhu tubuh',
                'opsi_b' => 'Membantu pergerakan tubuh',
                'opsi_c' => 'Menghasilkan hormon',
                'opsi_d' => 'Menyaring racun dalam darah',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Sistem otot memungkinkan tubuh untuk bergerak melalui kontraksi otot-otot yang melekat pada rangka.',
            ],
            [
                'slug' => 'sistem-otot',
                'nomor' => 2,
                'pertanyaan' => 'Jenis otot manakah yang bekerja tanpa kesadaran dan ditemukan di organ dalam?',
                'opsi_a' => 'Otot lurik',
                'opsi_b' => 'Otot polos',
                'opsi_c' => 'Otot rangka',
                'opsi_d' => 'Otot antagonis',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Otot polos bekerja secara tidak sadar dan ditemukan di organ-organ dalam seperti usus dan pembuluh darah.',
            ],
            [
                'slug' => 'sistem-otot',
                'nomor' => 3,
                'pertanyaan' => 'Otot jantung termasuk jenis otot yang...',
                'opsi_a' => 'Bekerja sadar dan cepat lelah',
                'opsi_b' => 'Tidak memiliki inti sel',
                'opsi_c' => 'Bekerja tidak sadar dan tidak cepat lelah',
                'opsi_d' => 'Menempel pada tulang',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Otot jantung bekerja secara tidak sadar dan terus-menerus tanpa lelah memompa darah ke seluruh tubuh.',
            ],
            [
                'slug' => 'sistem-otot',
                'nomor' => 4,
                'pertanyaan' => 'Gerakan berlawanan antara otot bisep dan trisep disebut gerak...',
                'opsi_a' => 'Sinergis',
                'opsi_b' => 'Refleks',
                'opsi_c' => 'Otomatis',
                'opsi_d' => 'Antagonis',
                'jawaban' => 'D',
                'poin' => 10,
                'penjelasan' => 'Gerak antagonis adalah gerakan berlawanan, seperti antara otot bisep (menekuk) dan trisep (meluruskan).',
            ],
            [
                'slug' => 'sistem-otot',
                'nomor' => 5,
                'pertanyaan' => 'Otot yang menempel pada rangka dan berfungsi untuk menggerakkan bagian tubuh adalah...',
                'opsi_a' => 'Otot polos',
                'opsi_b' => 'Otot lurik',
                'opsi_c' => 'Otot jantung',
                'opsi_d' => 'Otot halus',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Otot lurik menempel pada tulang dan berfungsi untuk menggerakkan tubuh secara sadar.',
            ],

            // sistem saraf 
            [
                'slug' => 'sistem-saraf',
                'nomor' => 1,
                'pertanyaan' => 'Apa fungsi utama sistem saraf dalam tubuh manusia?',
                'opsi_a' => 'Mencerna makanan',
                'opsi_b' => 'Mengangkut oksigen',
                'opsi_c' => 'Mengatur dan mengoordinasikan aktivitas tubuh',
                'opsi_d' => 'Memompa darah',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Sistem saraf berfungsi mengatur dan mengoordinasikan seluruh aktivitas tubuh, termasuk gerakan, pikiran, dan respons terhadap rangsangan.',
            ],
            [
                'slug' => 'sistem-saraf',
                'nomor' => 2,
                'pertanyaan' => 'Bagian otak yang mengatur keseimbangan dan koordinasi gerakan adalah...',
                'opsi_a' => 'Serebrum',
                'opsi_b' => 'Medula oblongata',
                'opsi_c' => 'Serebelum',
                'opsi_d' => 'Hipotalamus',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Serebelum (otak kecil) bertugas mengatur keseimbangan dan koordinasi otot saat tubuh bergerak.',
            ],
            [
                'slug' => 'sistem-saraf',
                'nomor' => 3,
                'pertanyaan' => 'Saraf yang membawa informasi dari pancaindra ke otak disebut...',
                'opsi_a' => 'Saraf motorik',
                'opsi_b' => 'Saraf sensorik',
                'opsi_c' => 'Saraf simpatik',
                'opsi_d' => 'Saraf parasimpatik',
                'jawaban' => 'B',
                'poin' => 10,
                'penjelasan' => 'Saraf sensorik mengirimkan impuls dari reseptor (pancaindra) ke sistem saraf pusat untuk diproses.',
            ],
            [
                'slug' => 'sistem-saraf',
                'nomor' => 4,
                'pertanyaan' => 'Respon cepat terhadap rangsangan tanpa melalui otak disebut...',
                'opsi_a' => 'Gerak sadar',
                'opsi_b' => 'Gerak pasif',
                'opsi_c' => 'Gerak refleks',
                'opsi_d' => 'Gerak aktif',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Gerak refleks adalah respon cepat dan otomatis terhadap rangsangan yang hanya melibatkan sumsum tulang belakang, bukan otak.',
            ],
            [
                'slug' => 'sistem-saraf',
                'nomor' => 5,
                'pertanyaan' => 'Bagian dari neuron yang mengirimkan impuls ke neuron lain adalah...',
                'opsi_a' => 'Dendrit',
                'opsi_b' => 'Soma',
                'opsi_c' => 'Akson',
                'opsi_d' => 'Sinaps',
                'jawaban' => 'C',
                'poin' => 10,
                'penjelasan' => 'Akson adalah bagian dari neuron yang membawa impuls listrik keluar dari sel menuju neuron lain atau organ target.',
            ],

        ];

        foreach ($soals as $soal) {
            SoalPilgan::create($soal);
        }
    }
}
